# Service setup
- name: Setup service
  ansible.builtin.copy:
   src: catalogue.service
   dest: /etc/systemd/system/{{ component }}.service
       
- name: Start and enable {{ component }} service
  ansible.builtin.service:
   name: {{ component }}
   state: started
   enabled: yes
   daemon-reload: true